### PR TITLE
Fix extracting stack resolver (fixes #195)

### LINKED ISSUE #195: Installing helper binaries failed (Mac Homebrew)
--- Creating vim config symlinks
	~/.vimrc -> /Users/ed/.config/haskell-vim-now/.vimrc
	~/.vim   -> /Users/ed/.config/haskell-vim-now/.vim
--- Installing plugins using vim-plug...
--- Setting up GHC if needed...
	Stack bin path: /Users/ed/.local/bin
	Stack global path: /Users/ed/.stack
	Stack global config location: /Users/ed/.stack/global-project/stack.yaml
	Stack resolver: lts
	/Users/ed/.config/haskell-vim-now/.stack-bin -> /Users/ed/.local/bin
--- Installing helper binaries...
Plan construction failed.
*** Binary installation failed with error 1.
*** Aborting...

### PR DESCRIPTION
**Pull request by harendra-kumar**
'sed -r' command was not portable on Mac.

### CODE REVIEW

File: scripts/setup.sh [hunk 1]
```diff
@@ -5,7 +5,10 @@ SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 
 stack_resolver() {
   local DEFAULT_RESOLVER=lts
-  local CONFIGURED=$( sed -rn 's/^resolver:\s*(\S+).*$/\1/p' "$1" 2>/dev/null )
+  local CONFIGURED
+
+  CONFIGURED=$(awk '{if ($1 == "resolver:") {print $2}}' "$1") \
```
Comment (begriffs) [inline scripts/setup.sh]: Very cool to see how this works, I've never used awk actually. Just tried this in my terminal and sure enough it extracts the value of resolver when present or empty string when absent.

**Comment by begriffs** [comment]
Do you know how to reproduce the error that this fixes? I've always been able to run the installer locally...

**Comment by harendra-kumar** [comment]
There are a few possible error scenarios:

1. The default resolver that we choose (latest lts) requires some `extra-deps` to install the tools required by hvn, these extra-deps should not be present in the stack global-project stack.yaml.
2. Global project stack.yaml is using an old resolver and some extra-deps which are incompatible with the default resolver (latest lts) which is different from the configured resolver. This is the one being hit in the #195.
3. the resolver line is missing in stack.yaml, so stack commands fail. This can be used to easily detect that we did not catch the error before stack install was called.

**Comment by begriffs** [comment]
OK good to know. I'll get this merged.
